#===============================================================================

project_name: bdpgxupaper_4_variants_no_network_metrics
runner_class: RRunner

#===============================================================================

libraries:

#---------------------------------------

    -  name: marxanLibrary

#       repo_type: local_file
#       url: file:////Users/bill/D/Marxan

       repo_type: http_zip
       url: http://glass.eres.rmit.edu.au/tzar_input/biodivprobgen/Marxan.zip
       download_mode: ONCE

#===============================================================================

    #  Cloned from:
    #  project.2017_08_16_09_51_am.original_full.yaml
    #  in:
    #  /Users/bill/D/Projects/ProblemDifficulty/pkgs/bdpgxupaper/inst/yamlFiles

    #--------------------

base_params:

        #  BTL - 2014 12 28
        #  This variable captures the tzar output path to hand it to the
        #  tzar emulation code.
    full_output_dir_with_slash: $$output_path$$

    #--------------------
    #--------------------

        #  SET THIS VALUE EVERY TIME...
            #  Runset description to print in output since the runset name has
            #  to be short and tends to be cryptic.  The "|" should force the
            #  saved description string to include newlines in the string.
            #  If you don't want the newlines (i.e., you want one long string),
            #  then use a ">" in place of the "|".
    runset_description: |
        Small set of runs of a Xu hard scenario with error generation both
        on and off plus running simulated annealing and richness heuristic.

    runset_name: $$runset$$
    runset_abbrev: "bdpgSingleRunForTestAndDebug"

    run_id: $$run_id$$

    #--------------------

        #  If you're reading the Xu problem from a file in Xu's benchmark
        #  problem file format instead of
        #  generating it, you need to give the input file name and the
        #  cost of the correct solution (since it's not specified in the file).

    read_Xu_problem_from_Xu_bench_file: FALSE

    Xu_bench_infile_name:  "/Users/bill/D/Projects/ProblemDifficulty/data/Xu - problem difficulty datasets/frb30-15-msc with MSC 420/frb30-15-1.msc"
#"/Users/bill/Desktop/Papers downloaded/Problem difficulty/Problem difficulty datasets/Xu - problem difficulty datasets/frb30-15-msc with MSC 420/frb30-15-1.msc"

    given_correct_solution_cost: 420

    #--------------------

        #  NOTE that the choice of random seed in the yaml file is important
        #  for this single run test because the example creates a test problem
        #  based on drawing the control parameters from a random distribution.
        #  When the seed was 111, the test crashed with the message below.
        #  When I changed it to 701, it ran to completion.
        #       Failing:  max_possible_tot_num_links ( 3291 ) > maximum allowed ( 2000 ).
        #       Save workspace image to ~/D/rdv-framework/projects/rdvPackages/biodivprobgen/.RData? [y/n/c]:
        #  However, the fail was just what it was supposed to do when those
        #  parameters came up, so the yaml file could be changed to use 111
        #  instead of 701 if you want to induce a crash to test that error
        #  trapping.
#    seed: 701

        #  2017 12 06 - BTL
        #  Instead, you could just set the total number of links or spp
        #  to some tiny amount that was sure to fail.

    max_allowed_possible_tot_num_links: 1500
    max_allowed_num_spp: 2000

    #--------------------

    set_rand_seed_at_creation_of_all_new_major_objects: FALSE
    bdpg_run_init_rand_seed:   14329

#  tests for random seed setting routines

##x1 = set_new_or_forced_rand_seed_if_necessary (TRUE, "abc")
#    set_rand_seed_at_creation_of_all_new_major_objects: TRUE
#    bdpg_run_init_rand_seed:   1
#    cor_base_rsprob_rand_seed: 2
#    cor_base_rsrun_rand_seed:  3
#    app_base_rsprob_rand_seed: 4
#    app_base_rsrun_rand_seed:  5
#    cor_wrap_rsprob_rand_seed: 6
#    cor_wrap_rsrun_rand_seed:  7
#    app_wrap_rsprob_rand_seed: 8
#    app_wrap_rsrun_rand_seed:  9

##x2 = set_new_or_forced_rand_seed_if_necessary (TRUE, "abc", 123)
#    set_rand_seed_at_creation_of_all_new_major_objects: TRUE
##    bdpg_run_init_rand_seed:   10
#    cor_base_rsprob_rand_seed: 20
##    cor_base_rsrun_rand_seed:  30
##    app_base_rsprob_rand_seed: 40
##    app_base_rsrun_rand_seed:  50
#    cor_wrap_rsprob_rand_seed: 60
##    cor_wrap_rsrun_rand_seed:  70
##    app_wrap_rsprob_rand_seed: 80
#    app_wrap_rsrun_rand_seed:  90


##x3 = set_new_or_forced_rand_seed_if_necessary (FALSE, "abc")
#    set_rand_seed_at_creation_of_all_new_major_objects: FALSE
#    bdpg_run_init_rand_seed:   100
#    cor_base_rsprob_rand_seed: 200
##    cor_base_rsrun_rand_seed:  300
#    app_base_rsprob_rand_seed: 400
#    app_base_rsrun_rand_seed:  500
##    cor_wrap_rsprob_rand_seed: 600
##    cor_wrap_rsrun_rand_seed:  700
#    app_wrap_rsprob_rand_seed: 800
#    app_wrap_rsrun_rand_seed:  900


##x4 = set_new_or_forced_rand_seed_if_necessary (FALSE, "abc", 123)
#    set_rand_seed_at_creation_of_all_new_major_objects: FALSE
##    bdpg_run_init_rand_seed:   1000
#    cor_base_rsprob_rand_seed: 2000
##    cor_base_rsrun_rand_seed:  3000
#    app_base_rsprob_rand_seed: 4000
##    app_base_rsrun_rand_seed:  5000
##    cor_wrap_rsprob_rand_seed: 6000
#    cor_wrap_rsrun_rand_seed:  7000
#    app_wrap_rsprob_rand_seed: 8000
#    app_wrap_rsrun_rand_seed:  9000

#  test of rerunning /Users/bill/tzar/outputdata/bdpgxupaper_4_variants_no_network_metrics/default_runset/30_marxan_simulated_annealing.completedTzarEmulation
#  Comparing marxan output err_frac etc showed that it seemed to work in duplicating the outcomes of cor, app, cor wrap, and app wrap
#    set_rand_seed_at_creation_of_all_new_major_objects: FALSE
#    bdpg_run_init_rand_seed:   870880126

    #--------------------

    integerize_string: "round"

    #---------------------------------------------------------------------------
        #  marxan control parameters
        #
        #  If marxan_use_default_input_parameters is TRUE, then all of these
        #  marxan_... parameters set in this file are ignored and marxan's
        #  default values are used instead.
        #  The one exception to this is the variable marxan_spf_const,
        #  which is a bit different from all the other parameters and is set
        #  in the just below the marxan_... parameters in this file.
    marxan_use_default_input_parameters: FALSE

#    marxan_input_parameters_file_name: "/Users/bill/D/Marxan/input.dat"
    marxan_input_parameters_file_name: "$$library_path(marxanLibrary)$$input.dat"

    marxan_dir: "$$library_path(marxanLibrary)$$"
#    marxan_input_dir: "$$library_path(marxanLibrary)$$input/"
#    marxan_output_dir: "$$library_path(marxanLibrary)$$output/"
    marxan_pu_file_name: "pu.dat"
    marxan_spec_file_name: "spec.dat"
    marxan_puvspr_file_name: "puvspr.dat"


    marxan_num_reps: 100
    marxan_num_iterations: "1000000"

#    marxan_num_reps: 1
#    marxan_num_iterations: "10000"

    marxan_spf_rule: "POWER_OF_10"

    #---------------------------------------------------------------------------

    compute_network_metrics: FALSE    #  if FALSE, overrides all other network flags below

    compute_network_metrics_COR: TRUE
    compute_network_metrics_APP: TRUE
    compute_network_metrics_wrapped_COR: TRUE
    compute_network_metrics_wrapped_APP: TRUE

    use_igraph_metrics:    TRUE

    use_bipartite_metrics: TRUE
    #bipartite_metrics_to_use:     "ALLBUTDD"
#    bipartite_metrics_to_use:     "all_except_slow_indices"
    bipartite_metrics_to_use:     "quick_test"

    #---------------------------------------------------------------------------

        # Outputs

#    summary_filename: prob_diff_results.csv
#    summary_without_run_id_filename: prob_diff_results_with_0_run_id.csv

    too_many_possible_links_error_flag_file_name: $$output_path$$too_many_possible_links_error_flag_file.txt

    #---------------------------------------------------------------------------
    #---------------------------------------------------------------------------

    gen_4_basic_variants: TRUE

    single_action_using_tzar_reps: FALSE    #TRUE

#    seed: 1000
#    gen_COR_prob: TRUE

#    seed: 1100
#    gen_WRAP_prob: TRUE
#    WRAP_input_prob_src: "rds_file_set_from_file"
#    WRAP_input_rds_file_set_path: "/Users/bill/Downloads/Tzar_input_files/COR_rds_input_file_paths.txt"

#    seed: 1200
#    gen_APP_prob: TRUE
#    APP_input_prob_src: "rds_file_set_from_file"
#    APP_input_rds_file_set_path: "/Users/bill/Downloads/Tzar_input_files/COR_rds_input_file_paths.txt"

#find /Users/bill/tzar/outputdata/bdpgxupaper_single_action_WRAP_prob/default_runset | grep saved > WRAP_rds_input_file_paths.txt
#    seed: 1300
#    gen_APP_prob: TRUE
#    APP_input_prob_src: "rds_file_set_from_file"
#    APP_input_rds_file_set_path: "/Users/bill/Downloads/Tzar_input_files/WRAP_rds_input_file_paths.txt"

#    seed: 1400
#    run_rs_on_COR_prob: TRUE
#    RS_cor_input_prob_src: "rds_file_set_from_file"
#    RS_cor_input_rds_file_set_path: "/Users/bill/Downloads/Tzar_input_files/COR_rds_input_file_paths.txt"

#find /Users/bill/tzar/outputdata/bdpgxupaper_single_action_APP_of_cor_base_prob/default_runset | grep saved > /Users/bill/Downloads/Tzar_input_files/APP_cor_rds_input_file_paths.txt
#    seed: 1500
#    run_rs_on_APP_prob: TRUE
#    RS_app_input_prob_src: "rds_file_set_from_file"
#    RS_app_input_rds_file_set_path: "/Users/bill/Downloads/Tzar_input_files/APP_cor_rds_input_file_paths.txt"
#    RS_app_base_input_rds_file_set_path: "/Users/bill/Downloads/Tzar_input_files/COR_rds_input_file_paths.txt"

#find /Users/bill/tzar/outputdata/bdpgxupaper_single_action_APP_of_cor_WRAP_prob/default_runset | grep saved > /Users/bill/Downloads/Tzar_input_files/APP_wrap_rds_input_file_paths.txt
#    seed: 1600
#    run_rs_on_APP_prob: TRUE
#    RS_app_input_prob_src: "rds_file_set_from_file"
#    RS_app_input_rds_file_set_path: "/Users/bill/Downloads/Tzar_input_files/APP_wrap_rds_input_file_paths.txt"
#    RS_app_base_input_rds_file_set_path: "/Users/bill/Downloads/Tzar_input_files/WRAP_rds_input_file_paths.txt"


#    seed: 1010
#    prob_src: "rds_file_set_from_yaml_array"
#    rds_file_set_yaml_array:
#        - "/Users/bill/tzar/outputdata/bdpgxupaper/default_runset/49_marxan_simulated_annealing/RSprob-COR-Base.fb9e78fc-5a6d-49b7-b8a9-74e918a86c92/saved.RSprob-COR-Base.fb9e78fc-5a6d-49b7-b8a9-74e918a86c92.rds"
#        - "/Users/bill/tzar/outputdata/bdpgxupaper/default_runset/51_marxan_simulated_annealing/RSprob-COR-Base.7151efe2-e13b-428b-ac76-62edc3b6b6a5/saved.RSprob-COR-Base.7151efe2-e13b-428b-ac76-62edc3b6b6a5.rds"
#        - "/Users/bill/tzar/outputdata/bdpgxupaper/default_runset/50_marxan_simulated_annealing/RSprob-COR-Base.0881452f-709a-4a4e-bd4c-9f502e1306c5/saved.RSprob-COR-Base.0881452f-709a-4a4e-bd4c-9f502e1306c5.rds"

    #---------------------------------------------------------------------------

scenarios:

            #-----------------------------------------------
            #  Xu simple model hard case:
            #      n in [8..100] while alpha = 0.52, r = 1
            #-----------------------------------------------

        #  Taken from v700 project.yaml scenario:
        #  scen_Xu_simple_model_hard_case_1__based_on_N

    - name: marxan_simulated_annealing
      parameters:
            marxan_runmode: 1
            marxan_heurtype: -1
#            marxan_num_reps: 2        #  TO SPEED UP SOME CURRENT TESTING
            marxan_num_reps: 100

            #--------------------

            derive_alpha_from_n__num_groups_and_opt_frac_0.5: TRUE

            use_unif_rand_n__num_groups: TRUE
            n__num_groups_lower_bound: 61
            n__num_groups_upper_bound: 80

            use_unif_rand_r__density: TRUE
            r__density_lower_bound: 0.01
            r__density_upper_bound: 5.0

            use_unif_rand_p__prop_of_links_between_groups: TRUE
            p__prop_of_links_between_groups_lower_bound: 0.01
            p__prop_of_links_between_groups_upper_bound: 0.99

            #--------------------

            apply_error_to_spp_occupancy_data: TRUE
#            match_error_counts: TRUE
            match_error_counts: FALSE

            #--------------------

                #  Constant errors

            spp_occ_FP_error_type: "CONSTANT"
            spp_occ_FP_const_rate: 0.0  #0.1

            spp_occ_FN_error_type: "CONSTANT"
            spp_occ_FN_const_rate: 0.1  #0.1

    #--------------------

                #  Parameters for building a multi-problem by wrapping a lognormal
                #  distribution around a base Xu problem.

            gen_multi_bdproblem: TRUE
            wrap_lognormal_dist_around_Xu: TRUE
            allow_imperfect_wrap: TRUE    #  new variable - BTL - 2017 12 13
            desired_Xu_spp_frac_of_all_spp: 0.5
            solution_frac_of_landscape: 0.3
            desired_max_abundance_frac: 0.7
            dep_set_PUs_eligible: FALSE
            add_one_to_lognormal_abundances: FALSE
#            seed_value_for_search: 11    #  no longer set this way - BTL - 2017 12 13
            max_search_iterations: 500

            plot_rounded_abundances: TRUE

    #---------------------------------------------------------------------------

#  COR prob generation
repetitions:
    generators:
        - key: seed        #rds_file_set_element_idx         #seed
          generator_type: linear_step
          start: 1                                  #1010
          step_size: 1
          count: 1  #00              #10

    #---------------------------------------------------------------------------

#  WRAP prob generation
#repetitions:
#    generators:
#        - key: rds_file_set_element_idx         #seed
#          generator_type: linear_step
#          start: 1        #1020        #1                                  #1010
#          step_size: 1
#          count: 5
#        - key: cur_input_prob_idx        #rds_file_set_element_idx         #seed
#          generator_type: linear_step
#          start: 1                                  #1010
#          step_size: 1
#          count: 3

    #---------------------------------------------------------------------------

#  APP (of COR base) prob generation
#repetitions:
#    generators:
#        - key: cur_input_prob_idx         #seed
#          generator_type: linear_step
#          start: 1        #1020        #1                                  #1010
#          step_size: 1
#          count: 5
#        - key: rds_file_set_element_idx         #seed
#          generator_type: linear_step
#          start: 1                                  #1010
#          step_size: 1
#          count: 2

    #---------------------------------------------------------------------------

#  APP (of COR base) prob generation
#repetitions:
#    generators:
#        - key: cur_input_prob_idx         #seed
#          generator_type: linear_step
#          start: 1        #1020        #1                                  #1010
#          step_size: 1
#          count: 15
#        - key: rds_file_set_element_idx         #seed
#          generator_type: linear_step
#          start: 1                                  #1010
#          step_size: 1
#          count: 2

    #---------------------------------------------------------------------------

#  Run marxan on COR base
#repetitions:
#    generators:
#        - key: cur_input_prob_idx         #seed
#          generator_type: linear_step
#          start: 1        #1020        #1                                  #1010
#          step_size: 1
#          count: 5

    #---------------------------------------------------------------------------

#  Run marxan on COR WRAP
#repetitions:
#    generators:
#        - key: cur_input_prob_idx         #seed
#          generator_type: linear_step
#          start: 1        #1020        #1                                  #1010
#          step_size: 1
#          count: 15

    #---------------------------------------------------------------------------

#  Run marxan on APP of COR base
#repetitions:
#    generators:
#        - key: cur_input_prob_idx         #seed
#          generator_type: linear_step
#          start: 1        #1020        #1                                  #1010
#          step_size: 1
#          count: 10

    #---------------------------------------------------------------------------

#  Run marxan on APP of WRAP base
#repetitions:
#    generators:
#        - key: cur_input_prob_idx         #seed
#          generator_type: linear_step
#          start: 1        #1020        #1                                  #1010
#          step_size: 1
#          count: 30

    #---------------------------------------------------------------------------

