#===============================================================================

project_name: TestGen6basicVariants
runner_class: RRunner

#===============================================================================

base_params:

    full_output_dir_with_slash: $$output_path$$

    runset_name:   $$runset$$
    runset_abbrev: "Test_gen_6"
    run_id:        $$run_id$$

    #--------------------

    gen_6_variants: TRUE

    #--------------------

    do_simple_richness_forward: TRUE

    #--------------------

    compute_network_metrics: FALSE    #  if FALSE, overrides all other network flags below

    compute_network_metrics_base_COR: TRUE
    compute_network_metrics_base_APP: TRUE
    compute_network_metrics_wrapped_COR: TRUE
    compute_network_metrics_wrapped_APP: TRUE

    use_igraph_metrics:    TRUE

    use_bipartite_metrics: TRUE
    #bipartite_metrics_to_use:     "ALLBUTDD"
    bipartite_metrics_to_use:     "all_except_slow_indices"
#    bipartite_metrics_to_use:     "quick_test"

    #---------------------------------------------------------------------------

repetitions:
    generators:
        - key: cur_run_idx
          generator_type: linear_step
          start: 1
          step_size: 1
          count: 1

    #---------------------------------------------------------------------------


#===============================================================================


