#===============================================================================

project_name: LoadExistingTzarRuns
runner_class: RRunner

#===============================================================================

libraries:

#---------------------------------------

    -  name: runs_to_load

#       repo_type: local_file
#       url: file:////Users/bill/D/Marxan

       repo_type: http_file
       url: http://glass.eres.rmit.edu.au/tzar_output/bdpg_nectar/TEST_loading_old/dirs.txt
       download_mode: FORCE

#===============================================================================

base_params:

    file_of_runs_to_load: $$library_path(runs_to_load)$$

    full_output_dir_with_slash: $$output_path$$

    runset_name:   $$runset$$
    runset_abbrev: "Easy_1_COR_prob"
    run_id:        $$run_id$$

    #--------------------

    bdpg_run_init_rand_seed: 1763688087

    #--------------------

    single_action_using_tzar_reps: TRUE
    gen_COR_prob: TRUE

    #--------------------

    n__num_groups: 5
    alpha__: 0.8
    p__prop_of_links_between_groups: 0.5
    r__density: 0.5

    #---------------------------------------------------------------------------

repetitions:
    generators:
        - key: prev_run_idx
          generator_type: linear_step
          start: 2
          step_size: 1
          count: 1

    #---------------------------------------------------------------------------


#===============================================================================


